"""
build_ics_threat_map.py   (ADDITIVE — reads two JSON files, writes one
Markdown reference table; touches no existing code)

Item C. Emits data/attacks/ics_threat_map.md: a reference table mapping the
domain-plausible attack set onto MITRE ATT&CK for ICS, with the realistic
grid consequence, severity, the a-priori expected defence layer, and the
layer that actually caught it in the routing evaluation. Regenerate any
time by re-running this script.

USAGE
    python src/build_ics_threat_map.py
"""

from __future__ import annotations

import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
ATTACKS = _ROOT / "data" / "attacks" / "domain_attacks.json"
EVAL = _ROOT / "data" / "results" / "domain_attack_eval.json"
OUT = _ROOT / "data" / "attacks" / "ics_threat_map.md"

CATEGORY_FRAME = {
    "direct_injection": ("OWASP LLM01 (direct)", "Instruction/authority override reaching the assessment logic"),
    "indirect_injection": ("OWASP LLM01 (indirect)", "Malicious guidance disguised as ordinary operational data"),
    "escalation": ("OWASP LLM01 + Ferrag et al. protocol exploit", "Injected attempt to trigger a control action / bypass approval"),
    "encoding_obfuscation": ("OWASP LLM01 + evasion", "Payload concealed to defeat pattern and drift detection"),
}


def main():
    attacks = json.loads(ATTACKS.read_text(encoding="utf-8"))["attacks"]
    actual = {}
    if EVAL.exists():
        for r in json.loads(EVAL.read_text(encoding="utf-8")).get("routing", []):
            actual[r["id"]] = ("blocked @ " + r["blocked_by"]) if r["blocked"] else "REACHED AGENT"

    lines = []
    lines.append("# Domain attacks — MITRE ATT&CK for ICS mapping\n")
    lines.append("_Generated by `src/build_ics_threat_map.py` from `domain_attacks.json` "
                 "and `domain_attack_eval.json`. Each attack instantiates a documented ICS "
                 "technique as text an LLM grid agent would ingest._\n")

    lines.append("## By attack category\n")
    lines.append("| Category | Framing | Grid-relevant meaning |")
    lines.append("|---|---|---|")
    for cat, (frame, meaning) in CATEGORY_FRAME.items():
        lines.append(f"| {cat} | {frame} | {meaning} |")
    lines.append("")

    lines.append("## By individual attack\n")
    lines.append("| ID | Category | ATT&CK for ICS technique | Realistic grid consequence | Severity | Expected layer | Actual result |")
    lines.append("|---|---|---|---|---|---|---|")
    for a in attacks:
        lines.append(
            f"| {a['id']} | {a['category']} | {a['ics_technique']} | "
            f"{a['grid_consequence']} | {a['severity']} | {a['expected_primary_layer']} | "
            f"{actual.get(a['id'], 'n/a')} |"
        )
    lines.append("")

    # quick technique tally
    from collections import Counter
    tally = Counter(a["ics_technique"].split(" (")[0] for a in attacks)
    lines.append("## Technique coverage\n")
    for tech, n in tally.most_common():
        lines.append(f"- {tech} — {n}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved -> {OUT}  ({len(attacks)} attacks, {len(tally)} distinct techniques)")


if __name__ == "__main__":
    main()
